### ISSUE TITLE
Peer-config should be defined via uploaded edn file

### ISSUE THREAD

**Issue by lbradstreet** [onyx-platform/onyx-benchmark#1]

**Comment by MichaelDrogalis** [comment]
@lbradstreet I didn't get to run the benchmark to test that this works, but I figured I'd kick start it for you. Patch is at https://github.com/onyx-platform/onyx-benchmark/commit/dd90b8a7987b3344f03ec71c5519a6a45464d3cf.

**Comment by MichaelDrogalis** [comment]
Done
